### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by cath1ynn** [Akrog/sqlexceller#1]
* Python version: 3.6
* Operating System: Windows server 2012

_The server details and connection details below have been removed for security reason_

sqlexceller "\\server\\SQL\Data.sql" -d mysql://username:password@host:port/database -o "\\server\\filename.xlsx"

<sqlalchemy.engine.result.ResultProxy object at 0x03AAA190>
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Scripts\sqlexceller.exe\__main__.py", line 9, in <module>
  File "c:\python\lib\site-packages\sqlexceller\sqlexceller.py", line 246, in main
    process_queries(cfg)
  File "c:\python\lib\site-packages\sqlexceller\sqlexceller.py", line 241, in process_queries
    output.write_query(query)
  File "c:\python\lib\site-packages\sqlexceller\sqlexceller.py", line 195, in write_query
    if row_data and self._column_titles:
UnboundLocalError: local variable 'row_data' referenced before assignment

**Comment by Akrog** [comment]
Thank you for reporting the issue.

That exception happens when one of the queries returns an empty result set, fixing it now.

**Comment by Akrog** [comment]
Fixed in v0.1.1: https://pypi.python.org/pypi/sqlexceller/0.1.1
